### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by neilisfragile** [element-hq/hydrogen-web#102]
**Describe the bug**
Log in is not possible, on attempting to do so the user is presented with an error "Cannot read property 'filter' of undefined"

**To Reproduce**
Attempt to log in

**Expected behaviour**
That I would be taken to a room (having been logged in)

**Screenshots**

![Screenshot 2020-09-21 at 11 48 50](https://user-images.githubusercontent.com/451032/93758503-79b00600-fc00-11ea-93d6-a41b41525682.png)

<img width="1382" alt="Screenshot 2020-09-21 at 11 41 23" src="https://user-images.githubusercontent.com/451032/93758354-3190e380-fc00-11ea-8769-c01ba9f73326.png">

Browser is latest Chrome on OSX

**Comment by bwindels** [comment]
This is the fix from https://github.com/vector-im/hydrogen-web/issues/15 that wasn't properly ported to the RoomSyncProcessState changes.

**Comment by bwindels** [comment]
Fix will be in next release (0.0.38)
