### ISSUE TITLE
Render replies correctly

### ISSUE THREAD

**Issue by bwindels** [element-hq/hydrogen-web#134]

**Comment by bwindels** [comment]
Would be cool to also show the number of replies on the target message, and allowing to click through to a right panel where you can see all the replies (and their replies?) for lightweight threading support. All while still rendering replies in the main timeline as well.

Or perhaps link to the reply in the main timeline if there is only 1 reply, and to the right panel if there are multiple.

**Comment by ptman** [comment]
What's still missing for showing correctly?

**Comment by DanilaFe** [comment]
For now, replies are rendered using the HTML fallback provided by clients. However, this may be spoofed, and also won't behave too nicely with messages that are, for instance, redacted after you reply to them. In addition, there's all the stuff Bruno outlined above.
