### ISSUE TITLE
Rooms are not left

### ISSUE THREAD

**Issue by bwindels** [element-hq/hydrogen-web#147]
We can start by keeping the left room around and just updating the membership in the room summary, and filtering those out
If we want to remove a room, it needs to be removed from:
 - timeline events
 - timeline fragments
 - room summary
 - room state
 - userIdentities
 - outgoing group session
 - incoming group sessions?
 - ...

**Comment by jasikpark** [comment]
It's interesting that when loading a new session, the currently left rooms are respected, but during a session they are not removed?

So while my https://hydrogren.element.io session shows way too many rooms, my http://localhost:3000 session shows my currently joined rooms w/o any extraneous ones.

**Comment by jasikpark** [comment]
Could https://matrix.org/docs/spec/client_server/latest#id287 be helpful, or is the information already pulled from [server]/_matrix/client/r0/sync?since=s1234567&timeout=30000&filter=0&_cacheBuster=987654321 ?

**Comment by jasikpark** [comment]
https://matrix.org/docs/spec/client_server/latest#id292 <- ah, so rooms that are left are not included in `/sync` unless `include_leave` is set to true

**Comment by bwindels** [comment]
yeah, leaving is just not implemented yet.
