### ISSUE TITLE
Could not set up secret storage with securityKey: Non-base58 character

### ISSUE THREAD

**Issue by mcnesium** [element-hq/hydrogen-web#163]
<img src="https://user-images.githubusercontent.com/476060/96336245-ada30d80-107e-11eb-8c15-3f24ecf96568.png" align="right" width="320" height="568" >

1. Go to https://hydrogen.element.io
2. Log in
3. Wait for the "Set up secret storage to decrypt older messages." popup
4. Click "enter security key"
5. enter security key in the popup form

**Expected behavior**
Session should be validated

**Actual behavior**
Error message "Could not set up secret storage with securityKey: Non-base58 character" appears. Session keeps unverified.

Seen on Safari/iOS 13 and Firefox 81/Linux

**Comment by bwindels** [comment]
Hmm, a recovery key should be 12 groups of 4 characters in the range of `123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz` separated by a space. Is this the case for your key?

**Comment by bwindels** [comment]
Was a case of mixing up the recovery key with the passphrase
