### ISSUE TITLE
Could not set up secret storage with passphrase: Bad MAC

### ISSUE THREAD

**Issue by mcnesium** [element-hq/hydrogen-web#164]
<img src="https://user-images.githubusercontent.com/476060/96336412-df68a400-107f-11eb-80b5-4b317f2637f7.png" align="right" width="320" height="568" >

1. Go to https://hydrogen.element.io
2. Log in
3. Wait for the "Set up secret storage to decrypt older messages." popup
4. Click "enter passphrase"
5. enter passphrase in the popup form

**Expected behavior**
Session should be validated

**Actual behavior**
Error message "Could not set up secret storage with passphrase: Bad MAC" appears. Session keeps unverified.

Seen on Safari/iOS 13 and Firefox 81/Linux

**Comment by bwindels** [comment]
This sounds like you entered the wrong password tbh. Are you 101% sure it was correct?

**Comment by mcnesium** [comment]
I copypasted it from the password store that I use to login on app.element.io as well, so I heavily assume it to be the same password…

**Comment by jryans** [comment]
Are you entering a recovery key or a passphrase? (Assuming passphrase, but just want to confirm...)

**Comment by mcnesium** [comment]
There are two links in the blue popup, right? When I hit "Enter passphrase", then I entered my passphrase of course. When I hit "enter security key", then I entered my recovery key that I also need to enter when I create a new browser session in app.element.io. The latter fails as well in hydrogen, which I reported in #163

**Comment by bwindels** [comment]
> I copypasted it from the password store that I use to login on app.element.io as well, so I heavily assume it to be the same password…

Note that the passphrase is not the same as your account password you use to login, although you might have set up secret storage with the passphrase being the same value as your account password.

**Comment by bwindels** [comment]
If not a mismatch between password and passphrase, I wonder if this could be a problem in the support of PBKDF2 on mobile Safari, although it [seems to be well supported](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto#Browser_compatibility), and the bac MAC error also doesn't suggest this.

**Comment by bwindels** [comment]
Was a case of mixing up the passphrase (or security phrase as element web calls it now) with the login password. Will update the wording to what element web uses to avoid confusion.
