### ISSUE TITLE
Only upload max/2 OTKs

### ISSUE THREAD

**Issue by bwindels** [element-hq/hydrogen-web#185]
So we keep the keys around for delayed olm messages. See crypto/index.js:1894 in js-sdk.

**Comment by bwindels** [comment]
might do max*0.75 rather to have as many OTKs on the server as we possibly can?

**Comment by tulir** [comment]
> might do max*0.75 rather to have as many OTKs on the server as we possibly can?

I initially thought this way too, but the reason for max/2 is that olm will forget old keys when you've generated more than max. With max/2, if you exhaust all OTKs while offline, you can safely upload a new batch before processing all the to-device events.
