### ISSUE TITLE
Firefox rejects fetch with AbortError, with cryptic service worker error

### ISSUE THREAD

**Issue by bwindels** [element-hq/hydrogen-web#187]
Splitting this issue off from https://github.com/vector-im/hydrogen-web/issues/184

So, to summarize, in Firefox, under certain conditions, the service worker encounters an error when trying to fetch a request to the homeserver. It unfortunately reports this as the cryptic `A ServiceWorker intercepted the request and encountered an unexpected error.` without further detail. From looking into the Sync and SessionContainer code, the only way the app would have gotten past the loading screen on the initial sync was if the request threw a DOMException with name AbortError (fixed getting past in 134f0188497d6ac7fa3e374f60011ba77bd6c396 and b8370d53b6522d26878b1402615e172a5d8b5d3a). I haven't been able to reproduce fetch throwing this while not calling abort on the abort controller from the app.

One reporter said they had  uBlockOrigin and PrivaccyBadger enabled when this happened, so perhaps an extension is at play. I tried to reproduce with uBlockOrigin but that would always throw a TypeError when blocking, not an AbortError.

**Comment by bwindels** [comment]
`A ServiceWorker intercepted the request and encountered an unexpected error.` corresponds to the firefox translation string `InterceptionFailedWithURL`, but there's very little information to be found when this is reported...

**Comment by bwindels** [comment]
Is https://bugzilla.mozilla.org/show_bug.cgi?id=1215140 related to this error?

**Comment by telmich** [comment]
I just had "this" problem - the login screen showed a hint to #187. I have quite some messages/rooms joined, at a 2nd try it worked.

**Comment by benparsons** [comment]
I had the same experience as previous comment - #187 error, then a refresh worked immediately. I have many many rooms.

**Comment by jasikpark** [comment]
I have yet to get this problem - Privacy Badger shows no trackers and I also run Ad Blocker Plus
(just to add a data point)

**Comment by freelock** [comment]
I'm getting this error too, trying to log into my account with close to 1000 rooms, in Firefox. I don't have any extra privacy blocker extensions installed.

In my browser console, I am seeing a CORS error -- I see Access-Control-Allow-Headers/Methods/Origin on the POST request to /_matrix/client/r0/user/<username>/filter, and a response, then a long wait on the GET /_matrix/client_r0/sync request that comes back with no Access-Control-Allow headers, and this request is blocked by the CORS error. Maybe something that can be fixed in Nginx?

**Comment by freelock** [comment]
I tried adding CORS headers to the server but this triggered a different error, multiple access control headers... but after removing that again, and refreshing another couple times it finally loaded up for me...

**Comment by bwindels** [comment]
ptman is also hitting this

**Comment by bwindels** [comment]
he reports:
actually, it just started working again, these errors aren't very reproducible
and usually logging out and back in helps

and runs privacy badger and ublock origin, not ad blocker plus

**Comment by bwindels** [comment]
for now, it's probably best to don't break the sync loop and sync again as the error is not persistent

**Comment by bwindels** [comment]
and add more logging when it does happen
