### ISSUE TITLE
Remember rooms in grid also after disabling it

### ISSUE THREAD

**Issue by almereyda** [element-hq/hydrogen-web#208]
**Is your feature request related to a problem? Please describe.**

When switching between grid and room view in Hydrogen, the selected rooms will be gone when returning.

**Describe the solution you'd like**

The selected rooms stay visible, as with closing the tab in grid view, and reopening the address at a later point.

**Describe alternatives you've considered**

We can choose to store certain grid view layouts, and/or tie grids to groups/spaces.

**Comment by bwindels** [comment]
Not sure how we want to evolve the grid view feature, will keep your suggestion into account when the time comes to decide, but will close this for now. Thanks!
