### ISSUE TITLE
Empty page with "SyntaxError: expected expression, got '.'" on Firefox 60esr and Chromium 73

### ISSUE THREAD

**Issue by Lomanic** [element-hq/hydrogen-web#230]
**Describe the bug**
Hydrogen is broken on Firefox 60esr and all versions before 74 and Chromium 73 and all versions before 80, the page is only blank.

**To Reproduce**
1. Go to https://hydrogen.element.io/ with Firefox 60esr (any version before 74, see below) or Chromium 73 (any version before 80, see below)
2. You are only greeted with an empty blank page
3. In the web console, the following error is raised
	  ```
	  SyntaxError: expected expression, got '.' 
	  hydrogen-1718798642.js:131:13
	  ```
**Expected behavior**
Page is properly displayed without issue

**Desktop:**
 - OS: GNU/Linux Debian 9.13 x64
 - Browser Firefox
 - Version 60.9.0esr (64 bits)

**Desktop:**
 - OS: GNU/Linux Debian 9.13 x64
 - Browser Chromium
 - Version 73.0.3683.75 (64 bits)

**Additional context**
Identical issue as https://github.com/matrix-org/matrix.to/issues/193 (fixed in https://github.com/matrix-org/matrix.to/commit/a4642540b4de9446628c2f9b0fa39c916c932769 that I tried to apply without success) but for Hydrogen, the same applies here.

**Comment by bwindels** [comment]
Thanks for reporting. This is because the build system assumes that anything that supports ES modules will support modern js syntax like `?.` (what somewhat older browsers choke on). Need to fix this by better feature detection ...

**Comment by bwindels** [comment]
Actually, we should compile down to only features supported by whatever version supports es modules for each browser. E.g. [async functions](https://caniuse.com/async-functions) and [classes](https://caniuse.com/es6-class) are supported everywhere [ES modules are supported](https://caniuse.com/es6-module), so they don't need to be compiled down. [Optional chaining is not](https://caniuse.com/mdn-javascript_operators_optional_chaining), so it should be transpiled down in the ES6 bundle.

**Comment by bwindels** [comment]
After some testing, the build [created with vite](#548) loads in Chrome 73 but not in Firefox 61 because it seems to choke on [this regex](https://github.com/vector-im/hydrogen-web/blob/d91aaabeb392b0b973525654ba98bc8b83063493/src/platform/web/Platform.js#L165) with the error `SyntaxError: invalid regexp group`. https://stackoverflow.com/questions/59488172/firefox-regex-syntaxerror-invalid-regexp-group and https://caniuse.com/js-regexp-lookbehind seem to explain this and I can confirm that the page does indeed load in Firefox 78. We should probably not use lookbehind.

**Comment by bwindels** [comment]
After replacing the lookbehind I was able to load the app in Firefox 63, well before Firefox 78 (can only do limited testing through test account on browserstack)

**Comment by bwindels** [comment]
The service-worker seems to fail to load on older browsers though, for the same reason as before (it is not transpiled and we use `?.`)
