### ISSUE TITLE
Verification not working

### ISSUE THREAD

**Issue by wireva** [element-hq/hydrogen-web#237]
**Describe the bug**
Verification of the new session not working

**To Reproduce**
Login and your other clients will ask you to verify the session. Click on "verify", it will just keep waiting and hydrogen does not accept the verification. 

**Expected behavior**
hydrogen should show some kind of verifiaction like qr code, text or emoji

**Screenshots**
not neccessary

**Desktop (please complete the following information):**
 - OS: Kubuntu 20.04
 - Browser: Firefox
 - Version: latest

**Comment by wireva** [comment]
uh just read the FAQ ^^

**Comment by heylix** [comment]
This is still a missing feature, even though the FAQ says that it's not implemented. Why did you close this? wontfix?

**Comment by genofire** [comment]
Element does not support verified manuelle across accounts (only on current account).
