### ISSUE TITLE
Join room

### ISSUE THREAD

**Issue by bwindels** [element-hq/hydrogen-web#28]
Join room from room directory & link.

This will allow hydrogen to be added to matrix.to as well

**Comment by ghost** [comment]
When it will come?

**Comment by ptman** [comment]
@ODIRFY Not a very useful comment, check out the project: https://github.com/vector-im/hydrogen-web/projects/1

**Comment by ghost** [comment]
> @ODIRFY Not a very useful comment, check out the project: https://github.com/vector-im/hydrogen-web/projects/1

Sorry, my fault.
