### ISSUE TITLE
Import a session throws an exception

### ISSUE THREAD

**Issue by germain-gg** [element-hq/hydrogen-web#332]
**Describe the bug**

Import a session fails and display an alert saying

```
this._createSessionContainer is not a fucntion
```

Stack trace

```
TypeError: this._createSessionContainer is not a function
    at SessionPickerViewModel.import (hydrogen-3360248282.js:16594)
    at HTMLButtonElement.onClick (hydrogen-3360248282.js:4454)
```

**To Reproduce**
1. Go in Firefox Desktop and export a session
2. Go in the PWA installed version of Hydrogen on Chrome desktop
3. Click "import" and upload the JSON

**Desktop (please complete the following information):**
 - OS: macOs
 - Browser: Chrome, Safari
 - Version: latests

**Comment by bwindels** [comment]
This feature is sort of known to be broken currently ... we should either remove the feature or fix it.

**Comment by bwindels** [comment]
this has been remove now
