### ISSUE TITLE
Errors building with docker

### ISSUE THREAD

**Issue by grahamPegNetwork** [element-hq/hydrogen-web#419]
**Describe the bug**
Errors while attempting to build with docker, per README. This was a clean checkout, terminal only following instructions.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser n/a
 - Version https://github.com/vector-im/hydrogen-web/commit/13932bb4802703764173271f8d96d2b64d03a166

Install log:

docker build -t hydrogen-dev -f Dockerfile-dev .
Sending build context to Docker daemon  18.87MB
Step 1/7 : FROM docker.io/node:alpine
alpine: Pulling from library/node
540db60ca938: Pull complete 
fe289da0f830: Pull complete 
c5a1e48e74e5: Pull complete 
63ccc02b1289: Pull complete 
Digest: sha256:50b33102c307e04f73817dad87cdae145b14782875495ddd950b5a48e4937c70
Status: Downloaded newer image for node:alpine
 ---> 4d2c046835fc
Step 2/7 : RUN apk add --no-cache git
 ---> Running in 132fadbc2b41
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
(1/7) Installing ca-certificates (20191127-r5)
(2/7) Installing brotli-libs (1.0.9-r3)
(3/7) Installing nghttp2-libs (1.42.0-r1)
(4/7) Installing libcurl (7.77.0-r1)
(5/7) Installing expat (2.2.10-r1)
(6/7) Installing pcre2 (10.36-r0)
(7/7) Installing git (2.30.2-r0)
Executing busybox-1.32.1-r6.trigger
Executing ca-certificates-20191127-r5.trigger
OK: 20 MiB in 23 packages
Removing intermediate container 132fadbc2b41
 ---> 3a2ed8d5599e
Step 3/7 : COPY . /code
 ---> 4803df5e751d
Step 4/7 : WORKDIR /code
 ---> Running in 2d013d49c5d2
Removing intermediate container 2d013d49c5d2
 ---> b23ba850371f
Step 5/7 : RUN yarn install
 ---> Running in fefbbf2c7304
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
**warning "fake-indexeddb > realistic-structured-clone > typeson@5.18.2" has unmet peer dependency "core-js-bundle@^3.6.4".**
[4/4] Building fresh packages...
$ node ./scripts/post-install.js
**(node:59) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Circular dependency: node_modules/es6-promise/lib/es6-promise/-internal.js -> node_modules/es6-promise/lib/es6-promise/then.js -> node_modules/es6-promise/lib/es6-promise/-internal.js
Circular dependency: node_modules/es6-promise/lib/es6-promise/-internal.js -> node_modules/es6-promise/lib/es6-promise/promise/resolve.js -> node_modules/es6-promise/lib/es6-promise/-internal.js
Circular dependency: node_modules/es6-promise/lib/es6-promise/promise.js -> node_modules/es6-promise/lib/es6-promise/promise/all.js -> node_modules/es6-promise/lib/es6-promise/enumerator.js -> node_modules/es6-promise/lib/es6-promise/promise.js
Circular dependency: node_modules/fake-indexeddb/build/FDBObjectStore.js -> node_modules/fake-indexeddb/build/FDBCursor.js -> node_modules/fake-indexeddb/build/FDBObjectStore.js
Circular dependency: node_modules/fake-indexeddb/build/FDBObjectStore.js -> node_modules/fake-indexeddb/build/FDBCursor.js -> /code/node_modules/fake-indexeddb/build/FDBObjectStore.js?commonjs-proxy -> node_modules/fake-indexeddb/build/FDBObjectStore.js**
Done in 25.74s.
Removing intermediate container fefbbf2c7304
 ---> 31a9ebcdefc1
Step 6/7 : EXPOSE 3000
 ---> Running in 62cf8019f850
Removing intermediate container 62cf8019f850
 ---> f7c7e7e584ed
Step 7/7 : ENTRYPOINT ["yarn", "start"]
 ---> Running in 7e142df934c8
Removing intermediate container 7e142df934c8
 ---> 1557d9c845f4
Successfully built 1557d9c845f4
Successfully tagged hydrogen-dev:latest

$ docker run \
>     --name hydrogen-dev \
>     --publish 3000:3000 \
>     --volume "$PWD":/code \
>     --interactive \
>     --tty \
>     --rm \
>     hydrogen-dev
yarn run v1.22.5
$ node scripts/serve-local.js
node:internal/modules/cjs/loader:930
  throw err;
  ^

Error: Cannot find module 'finalhandler'
Require stack:
- /code/scripts/serve-local.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:15)
    at Function.Module._load (node:internal/modules/cjs/loader:772:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/code/scripts/serve-local.js:17:22)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/code/scripts/serve-local.js' ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by bwindels** [comment]
Thanks for your report, but as mentioned in https://github.com/vector-im/hydrogen-web/blob/master/doc/docker.md, the docker instructions are not supported by the developers. You can try asking jcgruenhage on #hydrogen-web.
