### ISSUE TITLE
Losing connection and regaining it does not deliver messages (but only during local development)

### ISSUE THREAD

**Issue by DanilaFe** [element-hq/hydrogen-web#422]
**Describe the bug**
If I send a message while offline when doing local development, and then regain internet connection, the message does not send. Nor do subsequent messages. Refreshing doesn't quite fix it, but refreshing and sending another message does. Unable to replicate on `hydrogen.element.io`. 

**To Reproduce**
1. Simulate offline mode
2. Send a message
3. Return to being online'
4. Message does not send if doing local development

**Expected behavior**
Message should send as soon as internet connection is regained.

**Platform Info**
 - OS: (Arch) Linux
 - Browser: Firefox
 - Version: 89.0.2

**Comment by bwindels** [comment]
Would be good to get to the bottom of this though

**Comment by DanilaFe** [comment]
Looks like the cause is an exception during the call to `Session.start`. In particular, on my end, the error is:

```
Secret m.megolm_backup.v1 is not encrypted for key [key]
```

It's possible that something weird is stored into IDB, which is why things work fine on `hydrogen.element.io` (different IDB store) and another browser (Chromium)

**Comment by DanilaFe** [comment]
Looks like in particular, the error occurs while loading session backups. The data being requested from secret storage is `m.megolm_backup.v1`, and the "session backup" menu in the settings is stuck like this:

![Screenshot 2021-08-05 at 12-41-49 Screenshot](https://user-images.githubusercontent.com/4361282/128411423-a22ffff0-fa0e-4bfd-a128-af6b75c47e1e.png)

This further supports the "local storage is broken" hypothesis.

**Comment by DanilaFe** [comment]
Closing in favor of #449
