### ISSUE TITLE
Context menu can go offscreen when more than one option is present

### ISSUE THREAD

**Issue by DanilaFe** [element-hq/hydrogen-web#425]
**Describe the bug**
Opening a message's context menu (for reacting or deleting) at the bottom of the screen places the context menu very close to the bottom. With one additional option, such as replying, the context menu can go offscreen, and be inaccessible. For the last message in a chat, this makes it impossible to reach the context menu, since there's no way to scroll down to put more of it into view.

**To Reproduce**
1. Open a chat that takes up the entire screen and ends in one of your messages (to see the delete option)
2. Open the context menu of the bottom message
3. See that the context menu is partially off-screen

**Expected behavior**
Element web displays the context message "upwards" at the bottom and "downwards" at the top, thus preventing it from going out of bounds.

**Screenshots**
![Screenshot 2021-07-27 at 15-31-03 https hydrogen element io](https://user-images.githubusercontent.com/4361282/127235978-4c76d29e-acce-4996-a200-fb633dc6ff1e.png)
Current version of Hydrogen, delete button is accessible but approaching end of screen
![Screenshot 2021-07-27 at 15-31-19 Screenshot](https://user-images.githubusercontent.com/4361282/127236026-47396d96-e078-4738-937d-2157212faf15.png)
WIP replies version of Hydrogen, where the reply button pushes the delete button off-screen.

**Desktop:**
 - OS: Linux
 - Browser: Firefox
 - Version: 89.0.2

**Comment by bwindels** [comment]
Fixed in #509
