### ISSUE TITLE
State of Hydrogen

### ISSUE THREAD

**Issue by julianfairfax** [element-hq/hydrogen-web#430]
I've used Hydrogen as my main Matrix client on my PinePhone and I'm making this issue to report my findings in terms of features that are missing. I'm not sure if it would be productive to open a separate issue for each of the features that are missing but if you'd like I can do that. Missing features that have already been reported are linked in my lists. Thank you for all the work on this wonderful app and hopefully it will continue to get better!

Missing features
- Ignoring contacts #439
- Receiving read receipts #440
- Receiving typing indicators #441
- Sending and receiving calls #659 
- Changing profile settings #444
- Push notifications on GNOME Web #445

**Comment by bwindels** [comment]
Thanks for your report, it would indeed be better to open individual feature request issues.

**Comment by julianfairfax** [comment]
I will do that then. Thanks again.

**Comment by julianfairfax** [comment]
I've made those new issues and linked them here. The issue you opened for replies has also been linked.
