### ISSUE TITLE
Show read receipts in timeline

### ISSUE THREAD

**Issue by julianfairfax** [element-hq/hydrogen-web#440]
**Describe the solution you'd like**
It should be possible to see read receipts when someone reads a message like you can in the Element app.

**Additional context**
This is how the feature works in the Element app:
![image](https://user-images.githubusercontent.com/43753131/128203189-c219d342-5ee8-4ced-8ddf-609525058370.png)

**Comment by fnwbr** [comment]
"Read receipts" was maybe a better title... because not only "Showing read receipts" is missing, but also sending read receipts to the server is missing, right?

**Comment by julianfairfax** [comment]
> "Read receipts" was maybe a better title... because not only "Showing read receipts" is missing, but also sending read receipts to the server is missing, right?

Yes
