### ISSUE TITLE
Audio calls

### ISSUE THREAD

**Issue by julianfairfax** [element-hq/hydrogen-web#442]
**Describe the solution you'd like**
It should be possible to make audio calls like you can in the Element app.

**Additional context**
This is how the feature works in the Element app:
![image](https://user-images.githubusercontent.com/43753131/128203817-726b432c-6fcf-4310-aa9d-222be53ed6da.png)

**Comment by bwindels** [comment]
Closing in favour of https://github.com/vector-im/hydrogen-web/issues/659
