### ISSUE TITLE
Video calls

### ISSUE THREAD

**Issue by julianfairfax** [element-hq/hydrogen-web#443]
**Describe the solution you'd like**
It should be possible to make audio calls like you can in the Element app.

**Additional context**
This is how the feature works in the Element app:
![image](https://user-images.githubusercontent.com/43753131/128203911-badcbb7a-d1a3-4bcb-996b-e8b7eb1fe2d8.png)

**Comment by bwindels** [comment]
Closing in favour of https://github.com/vector-im/hydrogen-web/issues/659
