### ISSUE TITLE
Exception while loading secret storage and session backups

### ISSUE THREAD

**Issue by DanilaFe** [element-hq/hydrogen-web#449]
**Describe the bug**
When secret storage is being enabled, if the SSSS key generated by Hydrogen is no longer present in `m.megolm_backup` (I believe this happened when I reset my session backup), `enableSecretStorage` will throw with `Secret ... is not encrypted for key ...`. This error is not handled, and interrupts `Session.start` (breaking `SendQueue` and other synchronization things). Originally discovered as #422.

**To Reproduce**
Not quite certain about this, but:
1. Set up session backup in Hydrogen by importing secret key generated by Element.
2. Use Element to wipe your security keys (this is very destructive, be careful!)
3. Hydrogen should be broken now. The two symptoms I am aware of are not sending pending events after coming online, and "waiting to go online" being always displayed under "session backup" in settings.

**Expected behavior**
At the very least handling the exception without interrupting reconnection.

**Screenshots**
See #422 .

**Desktop:**
 - OS: Linux
 - Browser Firefox
 - Version: 89.0.2

**Comment by bwindels** [comment]
while looking at this, we might also have a look at deleting the session after login succeeds and any errors are thrown.
