### ISSUE TITLE
Can't open rooms with slashes in the ID

### ISSUE THREAD

**Issue by tulir** [element-hq/hydrogen-web#451]
**To Reproduce**
1. Join a room whose room ID contains a slash (`/`), e.g. [#test:maunium.net](https://matrix.to/#/#test:maunium.net) (room ID `!test/v7 🐈️:maunium.net`)
2. Try to open the room in Hydrogen
3. Hydrogen says "You are not currently in !test. Want to join it?"

**Expected behavior**
The room is opened and the user can send messages

**Screenshots**
![image](https://user-images.githubusercontent.com/4224639/129473307-d62b866e-fdb9-435c-8be1-b7e5cdb5b946.png)

**Smartphone (please complete the following information):**
 - Device: Nokia 8.3 5G
 - OS: Android 11
 - Browser: Firefox 91.0.0-beta.6
 - Version: 0.2.5

**Comment by bwindels** [comment]
I imagine it does work when your encodeURIComponent the room id?

**Comment by tulir** [comment]
Didn't think to try that earlier since I had installed Hydrogen as a PWA, but looks like it doesn't work:

![image](https://user-images.githubusercontent.com/4224639/129537583-d9b21c3e-0b2e-465a-a67b-3bb86693762a.png)
