### ISSUE TITLE
run with python server

### ISSUE THREAD

**Issue by vinniec** [element-hq/hydrogen-web#452]
This is a strange request, i know, but just today i managed to make element go through `python3 -m http.server` but not for hydrogen-web
Does anyone know how this can be done?

**Comment by bwindels** [comment]
I suppose this should work if you point it at the right folder (e.g target/ if you build it yourself), but this is a bit out of scope for the issue tracker here, so closing.

**Comment by vinniec** [comment]
i used the latest release (0.2.5), this is the output of the python server when i try to reach the page with a browser (i tried both firefox and chromium)"
```
# python3 -m http.server
Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
127.0.0.1 - - [16/Aug/2021 12:43:33] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [16/Aug/2021 12:43:34] "GET /hydrogen-1269016049.css HTTP/1.1" 200 -
127.0.0.1 - - [16/Aug/2021 12:43:34] "GET /themes/element/bundle-4174240642.css HTTP/1.1" 200 -
127.0.0.1 - - [16/Aug/2021 12:43:34] "GET /themes/bubbles/bundle-4020880164.css HTTP/1.1" 200 -
127.0.0.1 - - [16/Aug/2021 12:43:34] "GET /hydrogen-1310332091.js HTTP/1.1" 200 -
127.0.0.1 - - [16/Aug/2021 12:43:34] "GET /themes/element/inter/Inter-Regular-441590695.woff2 HTTP/1.1" 200 -
127.0.0.1 - - [16/Aug/2021 12:43:34] "GET /icon-maskable-317721575.png HTTP/1.1" 200 -
127.0.0.1 - - [16/Aug/2021 12:43:34] code 404, message File not found
127.0.0.1 - - [16/Aug/2021 12:43:34] "GET /favicon.ico HTTP/1.1" 404 -
```
But is there a reason why a webserver has to be necessary? Couldn't the app be made usable also without it and only with a browser?
