### ISSUE TITLE
The createRouter method arguments order is wrong

### ISSUE THREAD

**Issue by svieujot** [element-hq/hydrogen-web#476]
In `src/domain/navigation/index.js`, the `createRouter` calls 
```
return new URLRouter({history, navigation, stringifyPath, parseUrlPath});
```
But the `URLRouter`'s constructor is : 
```
constructor({history, navigation, parseUrlPath, stringifyPath})
```
i.e. the `stringifyPath` and `parseUrlPath` are inverted.

**Comment by bwindels** [comment]
With named parameters, the order is not really of any importance.
