### ISSUE TITLE
.well-known not working

### ISSUE THREAD

**Issue by spaetz** [element-hq/hydrogen-web#478]
**Describe the bug**
My matrix server is on a subdomain, while user accounts are using the main domain name. hydrogen 0.2.7 queries `MAINDOMAIN/.well-known/matrix/client `when I enter the main domain as homeserver, but then fails to contact the matrix server, printing
_Could not query login methods supported by MAINDOMAIN_

**To Reproduce**

1. Open https://hydrogen.element.io
2. Enter `sspaeth.de` as homeserver
3. The webbrowser will now query https://sspaeth.de/.well-known/matrix/client which returns (without mime type is that an issue?)
```
{
  "m.homeserver": {
    "base_url": "https://sursulapitsch.sspaeth.de"
  },
}
```
4. "Could not query login methods supported by sspaeth.de"

When I enter "sursulapitsch.sspaeth.de" as homeserver, everything is fine. https://sspaeth.de/.well-known/matrix/client sends the CORS headers:
```
access-control-allow-methods: GET,POST,OPTIONS,DELETE,PUT
access-control-allow-origin: *
```

Is there something obvious I have been overlooking?

**Comment by aaronraimist** [comment]
That isn't valid JSON. You have an extra comma.
