### ISSUE TITLE
SSO Login

### ISSUE THREAD

**Issue by ptman** [element-hq/hydrogen-web#93]
SAML / OpenID Connect login support

**Comment by bwindels** [comment]
Hey, thanks for filing an issue, but I would rather not have a feature request issue in here for every missing feature that is not on the immediate roadmap, so closing this for now.

**Comment by bwindels** [comment]
Probably best to raise and discuss feature requests in #hydrogen:matrix.org come to think of it.

**Comment by bwindels** [comment]
Also see https://matrix.org/docs/guides/sso-for-client-developers

**Comment by tawfiek** [comment]
Assign it to me @bwindels

**Comment by tawfiek** [comment]
As discussed with @bwindels 

He suggest : 

> Adding a method `startLogin(server)` to `SessionContainer` that returns a Login object to which the response from the server is passed. Depending on the flows, it could have an sso property and password property with objects that have methods for those specific login mechanisms

And for UX and Component structure, we came out with two suggestions : 
 * 1st
   Make the current  `LoginView`  is the root of the application which takes the `homeserver` URL Then load buttons of supported login methods that linked with individual view  for every  method.

```
LoginView
  homeserver field
  if supported: PasswordLoginView
  if suppoted: SSOLoginView
```
 * 2nd 
 Make another parent component for the current `LoginView` called for example `ClientConfig` that takes `homeserver`  as a user input gets the supported methods and render `LoginView` shows all supported login options just like in Element web. 
 
```
ClientConfig
    homeserver field
    set state
    LoginView
```

**Comment by bwindels** [comment]
Was a bit overly optimistic of me to mark this as a good-first-issue, the changes are quite involved and there isn't a lot of documentation to work with.

**Comment by bwindels** [comment]
I have made some notes on how I expect the feature should work on https://github.com/vector-im/hydrogen-web/blob/master/doc/impl-thoughts/SSO.md
